apiVersion: v1
kind: Pod
metadata:
  name: mytemplate-rails
spec:
  containers:
    - name: app
      image: mytemplate-rails
      command: ["irb"]
      ports:
        - containerPort: 3000
          hostPort: 3000
      volumeMounts:
        - name: app-volume
          mountPath: /rails:Z
      workingDir: /rails
      env:
        - name: RAILS_ENV
          value: development
        - name: TZ
          value: Asia/Tokyo
      tty: true
    - name: db
      image: mysql:8.4
      ports:
        - containerPort: 3306
          hostPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: TZ
          value: Asia/Tokyo
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql

  volumes:
    - name: app-volume
      hostPath:
        path: ./
    - name: db-data
      persistentVolumeClaim:
        claimName: db-pv-claim
